directories:
  output: dist_electron
  buildResources: build
appId: com.sharpen.webpconverter
productName: Sharpen WebP Converter
files:
  - filter:
      - dist/**/*
      - electron/**/*
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  installerIcon: public/icon.ico
  uninstallerIcon: public/icon.ico
  license: LICENSE
  shortcutName: Sharpen WebP Converter
electronVersion: 29.4.6
